name: Build LabApiExtensions

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:
    # allows manual trigger

env:
  ProjName: CustomRespawnWaves.TestWave
  REFERENCES_URL: https://exmod-team.github.io/SL-References/Dev.zip
  REFERENCES_PATH: ${{ github.workspace }}/References

jobs:
  build:
    runs-on: windows-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 9.0.x

      - name: Download References
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ env.REFERENCES_URL }} -OutFile "${{ github.workspace }}/References.zip"
          Expand-Archive -Path "${{ github.workspace }}/References.zip" -DestinationPath ${{ env.REFERENCES_PATH }}

      - name: Rename Assembly-CSharp-Publicized to Assembly-CSharp
        shell: pwsh
        run: |
            Rename-Item -Path "${{ env.REFERENCES_PATH }}\Assembly-CSharp-Publicized.dll" -NewName "Assembly-CSharp.dll"
            
      - name: Build
        env:
          SL_REFERENCES: ${{ env.REFERENCES_PATH }}
        shell: pwsh
        run: |
          dotnet build ${{ env.ProjName }}/${{ env.ProjName }}.csproj -c Release -o:Out

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: CustomRespawnWaves
          path: Out
          if-no-files-found: error
