name: Publish
on:
  push:
    tags:
      - "release-*"

env:
  ProjName: CustomRespawnWaves
  REFERENCES_URL: https://exmod-team.github.io/SL-References/Dev.zip
  REFERENCES_PATH: ${{ github.workspace }}/References

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Download References
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ env.REFERENCES_URL }} -OutFile "${{ github.workspace }}/References.zip"
          Expand-Archive -Path "${{ github.workspace }}/References.zip" -DestinationPath ${{ env.REFERENCES_PATH }}

      - name: Rename Assembly-CSharp-Publicized to Assembly-CSharp
        shell: pwsh
        run: |
            Rename-Item -Path "${{ env.REFERENCES_PATH }}\Assembly-CSharp-Publicized.dll" -NewName "Assembly-CSharp.dll"       

      - name: Build
        env:
          SL_REFERENCES: ${{ env.REFERENCES_PATH }}
        run: dotnet build ${{ env.ProjName }}/${{ env.ProjName }}.csproj -o Out

      - name : Upload
        uses: actions/upload-artifact@v4.3.5
        with:
          name: ${{ env.ProjName }}
          path: Out

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: Out/**